### PR TITLE
Corrected socket.io

### LINKED ISSUE #3: Incorrect calling of socket.io
Please assign me this task, i'll try fixing it

### PR DESCRIPTION
**Pull request by ritishab0209**
Please look into the corrected code and merge the request

Closes https://github.com/OshadhaVimuB/ChitChat/issues/3

### CODE REVIEW

**Comment by OshadhaVimuB** [comment]
Did you check the code? It didn't work for me.

**Comment by ritishab0209** [comment]
What problem did you face

**Comment by ritishab0209** [comment]
Please look into the changed code and merge it

**Review by OshadhaVimuB — APPROVED** [review]

**Comment by OshadhaVimuB** [comment]
Thank You

**Pull request merged**
